version: 0.1

phases:
  install:
   commands:
     - echo Entering install phase...
     - echo Nothing to do now
  build:
    commands:
     - ./gradlew clean installEc2Dist
artifacts:
  discard-paths: yes
  files:
    - 'build/install/callableapis-webapp-ec2/**/*'
