version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
     - ./gradlew clean installEc2Dist
artifacts:
  base-directory: 'build/install/callableapis-webapp-ec2'
  files:
    - '**/*'
