version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - echo Building the WAR file...
      - ./gradlew clean war
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Build phase completed
artifacts:
  base-directory: "build/libs"
  files:
    - "ROOT.war"
    - "**/*"
