version: "3.8"

services:
  callableapis:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
    volumes:
      - ./logs:/usr/local/tomcat/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/calendar/date"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
