/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.callableapis.api;

import com.callableapis.api.handlers.v1.CalendarResource;
import org.junit.Assert;
import org.junit.Test;
import static org.junit.Assert.*;

public class CalendarResourceTest {

    @Test
    public void testGetDateAsStruct() {
        CalendarResource resource = new CalendarResource();

        CalendarResource.DateStruct struct = resource.getDateAsStruct();
        Assert.assertNotNull(struct);
    }
}
