/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.callableapis.api;

import org.glassfish.grizzly.http.server.HttpServer;
import org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory;

import java.net.URI;

public class App {
    private static final String BIND_URL_PROPERTY_NAME = "com.callableapis.bindurl";
    private static final String BIND_URL_DEFAULT_VALUE = "http://localhost:8080/";

    public void runServer() {
        String bindUrl = System.getProperty(BIND_URL_PROPERTY_NAME, BIND_URL_DEFAULT_VALUE);

        URI uri = URI.create(bindUrl);
        HttpServer server = GrizzlyHttpServerFactory.createHttpServer(uri, new APIApplication());
        Runtime.getRuntime().addShutdownHook(new Thread(server::shutdownNow));

        try {
            server.start();
            Thread.currentThread().join();
        } catch (InterruptedException e) {
            ;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        App app = new App();
        app.runServer();
    }
}
