name: CI

on:
  push:
    branches: [ main, master, '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Checkstyle
        run: ./gradlew --no-daemon checkstyleMain checkstyleTest

      - name: Upload Checkstyle reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-reports
          path: |
            build/reports/checkstyle/*.xml
            build/reports/checkstyle/*.html

  spotbugs:
    name: SpotBugs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run SpotBugs
        run: ./gradlew --no-daemon spotbugsMain spotbugsTest

      - name: Upload SpotBugs reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-reports
          path: |
            build/reports/spotbugs/*.html
            build/reports/spotbugs/*.xml

  tests:
    name: Tests and Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run unit tests
        run: ./gradlew --no-daemon test

      - name: Generate JaCoCo report
        run: ./gradlew --no-daemon jacocoTestReport

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            build/test-results/test/**/*.xml
            build/reports/tests/test/**

      - name: Upload Coverage Reports (JaCoCo)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-reports
          path: |
            build/reports/jacoco/test/jacocoTestReport.xml
            build/reports/jacoco/test/html/**
